name: Linux CI

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  ci-linux:
    uses: cpslabgu/swift-workflows/.github/workflows/ci-linux.yml@main
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.WORKFLOWS_SSH_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.WORKFLOWS_SSH_PUBLIC_KEY }}
