name: Swift Lint 

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]
  workflow_dispatch:

jobs:
  swiftlint:
    uses: cpslabgu/swift-workflows/.github/workflows/swiftlint.yml@main
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.WORKFLOWS_SSH_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.WORKFLOWS_SSH_PUBLIC_KEY }}
