name: Swift Lint 

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  swiftlint:
    uses: cpslabgu/swift-workflows/.github/workflows/swiftlint.yml@main
    secrets: inherit
